// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozg7I0MSaSBw4ea9_RviBaIUPPRpFTnI',
    appId: '1:1095188614950:web:80c704f84d70b9a20abbe7',
    messagingSenderId: '1095188614950',
    projectId: 'secu-24360',
    authDomain: 'secu-24360.firebaseapp.com',
    storageBucket: 'secu-24360.appspot.com',
    measurementId: 'G-6FWMT7NQZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5mSQ3-Y-EKNJPUZzVdxgBk7U692fSwM',
    appId: '1:1095188614950:android:1d64fa09d1a0ecf70abbe7',
    messagingSenderId: '1095188614950',
    projectId: 'secu-24360',
    storageBucket: 'secu-24360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChG1DtuPhXDC3mBBFvl4CjVif8QnbmvU',
    appId: '1:1095188614950:ios:a4cbfdecdd6d26d70abbe7',
    messagingSenderId: '1095188614950',
    projectId: 'secu-24360',
    storageBucket: 'secu-24360.appspot.com',
    iosBundleId: 'com.example.secunity2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChG1DtuPhXDC3mBBFvl4CjVif8QnbmvU',
    appId: '1:1095188614950:ios:a836b4cf2cfda37c0abbe7',
    messagingSenderId: '1095188614950',
    projectId: 'secu-24360',
    storageBucket: 'secu-24360.appspot.com',
    iosBundleId: 'com.example.secunity2.RunnerTests',
  );
}
